"""
Bug Bounty Report Generator.
Converts scan findings into professional Markdown + HTML reports ready for
HackerOne / Bugcrowd / Synack submissions.
"""
from datetime import datetime, timezone
from typing import Dict, List


SEVERITY_ORDER = {'critical': 4, 'high': 3, 'medium': 2, 'low': 1, 'info': 0}


def _md_escape(s: str) -> str:
    if not s:
        return ''
    return str(s).replace('|', '\\|').replace('\r', '')


def generate_markdown_report(scan: Dict, findings: List[Dict],
                              attack_chains: List[Dict] = None,
                              recon: Dict = None,
                              include_unverified: bool = False) -> str:
    """Generate a full Markdown bug bounty report."""
    lines = []
    target = scan.get('target', 'unknown')
    scan_id = scan.get('id') or scan.get('scan_id', '')
    started = scan.get('started_at') or datetime.now(timezone.utc).isoformat()
    summary = scan.get('summary', {})

    # Header
    lines.append(f'# 🔴 Security Assessment Report — `{target}`')
    lines.append('')
    lines.append('> **Generated by CyberScope v7.2** — Automated web vulnerability audit')
    lines.append('')
    lines.append(f'- **Target:** `{target}`')
    lines.append(f'- **Scan ID:** `{scan_id}`')
    lines.append(f'- **Date:** {started}')
    lines.append(f'- **Total findings:** {summary.get("total", len(findings))}')
    lines.append(f'- **Critical:** {summary.get("critical", 0)} · '
                 f'**High:** {summary.get("high", 0)} · '
                 f'**Medium:** {summary.get("medium", 0)} · '
                 f'**Low:** {summary.get("low", 0)}')
    lines.append('')

    # Executive summary
    verified_findings = [f for f in findings if f.get('verified')]
    lines.append('## 📊 Executive Summary')
    lines.append('')
    lines.append(f'This assessment identified **{len(verified_findings)} verified** security findings '
                 f'on `{target}`. The most impactful issues are listed below by severity.')
    lines.append('')

    # Findings table
    scope = findings if include_unverified else verified_findings
    scope = sorted(scope, key=lambda f: -SEVERITY_ORDER.get((f.get('severity') or 'info'), 0))
    if scope:
        lines.append('## 🎯 Findings Overview')
        lines.append('')
        lines.append('| # | Severity | Type | Verified | CVSS | URL |')
        lines.append('|---|----------|------|----------|------|-----|')
        for i, f in enumerate(scope, 1):
            v = '✅' if f.get('verified') else '⚠️'
            url_short = (f.get('url') or '')[:60] + ('…' if len(f.get('url') or '') > 60 else '')
            lines.append(f'| {i} | {f.get("severity", "info").upper()} | '
                         f'{f.get("type", "")}·{f.get("subtype", "") or ""} | {v} | '
                         f'{f.get("cvss", 0)} | `{_md_escape(url_short)}` |')
        lines.append('')

    # Detailed findings
    lines.append('## 🔍 Detailed Findings')
    lines.append('')
    for i, f in enumerate(scope, 1):
        lines.append(f'### {i}. [{(f.get("severity") or "info").upper()}] {f.get("name") or f.get("type")}')
        lines.append('')
        lines.append(f'- **Type:** `{f.get("type")}`' + (f' · `{f.get("subtype")}`' if f.get('subtype') else ''))
        lines.append(f'- **Verified:** {"✅ Yes" if f.get("verified") else "⚠️ Requires manual verification"}')
        lines.append(f'- **CVSS Score:** {f.get("cvss", 0)}')
        lines.append(f'- **Confidence:** {f.get("confidence", 0)}%')
        if f.get('cve'):
            lines.append(f'- **CVE:** `{f.get("cve")}`')
        if f.get('url'):
            lines.append(f'- **URL:** `{_md_escape(f.get("url"))}`')
        if f.get('param'):
            lines.append(f'- **Parameter:** `{f.get("param")}`')
        if f.get('method'):
            lines.append(f'- **Method:** `{f.get("method")}`')
        lines.append('')
        if f.get('desc') or f.get('note'):
            lines.append('**Description:**')
            lines.append('')
            lines.append(f.get('desc') or f.get('note'))
            lines.append('')
        if f.get('payload'):
            lines.append('**Payload:**')
            lines.append('')
            lines.append('```')
            lines.append(str(f.get('payload'))[:500])
            lines.append('```')
            lines.append('')
        if f.get('evidence'):
            lines.append('**Evidence:**')
            lines.append('')
            lines.append('```')
            lines.append(str(f.get('evidence'))[:1000])
            lines.append('```')
            lines.append('')
        if f.get('explanation'):
            # If AI explanation was attached
            lines.append('**Analysis:**')
            lines.append('')
            lines.append(f.get('explanation'))
            lines.append('')
        lines.append('---')
        lines.append('')

    # Attack chains
    if attack_chains:
        lines.append('## 🔗 Attack Chains')
        lines.append('')
        lines.append('The following multi-step exploitation chains can be constructed from the verified findings:')
        lines.append('')
        for c in attack_chains:
            lines.append(f'### ⛓️ {c.get("name")}')
            lines.append('')
            lines.append(f'- **Severity:** {c.get("severity", "").upper()}')
            lines.append(f'- **CVSS:** {c.get("cvss", 0)}')
            lines.append(f'- **Confidence:** {c.get("confidence", 0)}%')
            lines.append('')
            lines.append('**Exploit Sequence:**')
            lines.append('')
            for j, s in enumerate(c.get('steps', []), 1):
                lines.append(f'{j}. {s}')
            lines.append('')
            if c.get('mitigation'):
                lines.append('**Mitigation:**')
                lines.append('')
                for m in c.get('mitigation', []):
                    lines.append(f'- {m}')
                lines.append('')
            lines.append('---')
            lines.append('')

    # Reconnaissance
    if recon:
        lines.append('## 🕵️ Reconnaissance Summary')
        lines.append('')
        crawler = recon.get('crawler', {})
        lines.append(f'- Pages crawled: **{crawler.get("visited_count", 0)}**')
        lines.append(f'- Endpoints discovered: **{len(crawler.get("endpoints", []))}**')
        lines.append(f'- Parameters found: **{len(crawler.get("params_found", []))}**')
        lines.append(f'- Forms discovered: **{len(crawler.get("forms", []))}**')
        lines.append(f'- Sitemap URLs: **{crawler.get("sitemap_urls_count", 0)}**')
        lines.append('')

    # Footer
    lines.append('---')
    lines.append('')
    lines.append('_Report generated automatically by [CyberScope v7.2](https://github.com/) — a weaponized web vulnerability auditor._')
    lines.append('')
    lines.append('**Legal notice:** This report is for authorized security testing only. '
                 'Unauthorized scanning is illegal under CFAA, GDPR, and similar laws.')

    return '\n'.join(lines)


def _html_escape(text: str) -> str:
    """SEC-003 · Full HTML escape including quotes for attribute contexts."""
    if not isinstance(text, str):
        text = str(text or '')
    return (text.replace('&', '&amp;')
                .replace('<', '&lt;')
                .replace('>', '&gt;')
                .replace('"', '&quot;')
                .replace("'", '&#39;'))


def generate_html_report(scan: Dict, findings: List[Dict],
                         attack_chains: List[Dict] = None,
                         recon: Dict = None,
                         include_unverified: bool = False) -> str:
    """Generate a self-contained HTML report."""
    md = generate_markdown_report(scan, findings, attack_chains, recon, include_unverified)

    # Minimal Markdown → HTML converter (no external deps)
    html_body = _md_to_html(md)

    safe_target = _html_escape(scan.get('target', 'unknown'))
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:; font-src 'self';">
<meta name="referrer" content="no-referrer">
<title>Security Report — {safe_target}</title>
<style>
  * {{ box-sizing: border-box; }}
  body {{ font-family: -apple-system, 'Segoe UI', Roboto, sans-serif; max-width: 900px;
    margin: 40px auto; padding: 0 20px; color: #1f2937; line-height: 1.6; background: #f9fafb; }}
  h1 {{ color: #dc2626; border-bottom: 3px solid #dc2626; padding-bottom: 10px; }}
  h2 {{ color: #dc2626; margin-top: 40px; }}
  h3 {{ color: #111827; margin-top: 30px; }}
  code {{ background: #f3f4f6; padding: 2px 6px; border-radius: 3px;
    font-family: 'SF Mono', 'Consolas', monospace; font-size: 0.9em; color: #dc2626; }}
  pre {{ background: #1f2937; color: #10b981; padding: 15px; overflow-x: auto;
    border-radius: 6px; font-size: 0.85em; }}
  pre code {{ background: transparent; color: inherit; padding: 0; }}
  table {{ border-collapse: collapse; width: 100%; margin: 20px 0; background: #fff;
    box-shadow: 0 1px 3px rgba(0,0,0,0.05); }}
  th, td {{ border: 1px solid #e5e7eb; padding: 10px 12px; text-align: left; }}
  th {{ background: #1f2937; color: #fff; font-weight: 600; }}
  tr:nth-child(even) {{ background: #f9fafb; }}
  hr {{ border: 0; border-top: 1px solid #e5e7eb; margin: 30px 0; }}
  blockquote {{ border-left: 4px solid #dc2626; padding-left: 15px; color: #6b7280;
    margin: 20px 0; font-style: italic; }}
  ul, ol {{ padding-left: 25px; }}
  a {{ color: #dc2626; }}
</style>
</head>
<body>
{html_body}
</body>
</html>"""


def _md_to_html(md: str) -> str:
    """Minimal, dependency-free Markdown→HTML converter (enough for our reports)."""
    import re
    html_lines = []
    in_code = False
    in_table = False
    for line in md.split('\n'):
        if line.startswith('```'):
            if in_code:
                html_lines.append('</code></pre>')
                in_code = False
            else:
                html_lines.append('<pre><code>')
                in_code = True
            continue
        if in_code:
            html_lines.append(line.replace('<', '&lt;').replace('>', '&gt;'))
            continue

        # Tables
        if '|' in line and re.match(r'^\|.*\|$', line.strip()):
            if not in_table:
                html_lines.append('<table>')
                in_table = 'header'
            cells = [c.strip() for c in line.strip().strip('|').split('|')]
            if in_table == 'header':
                html_lines.append('<thead><tr>' +
                                  ''.join(f'<th>{_inline_md(c)}</th>' for c in cells) +
                                  '</tr></thead><tbody>')
                in_table = 'separator'
            elif in_table == 'separator':
                # skip |---|---| separator
                in_table = 'body'
            else:
                html_lines.append('<tr>' + ''.join(f'<td>{_inline_md(c)}</td>' for c in cells) + '</tr>')
            continue
        else:
            if in_table:
                html_lines.append('</tbody></table>')
                in_table = False

        if line.startswith('### '):
            html_lines.append(f'<h3>{_inline_md(line[4:])}</h3>')
        elif line.startswith('## '):
            html_lines.append(f'<h2>{_inline_md(line[3:])}</h2>')
        elif line.startswith('# '):
            html_lines.append(f'<h1>{_inline_md(line[2:])}</h1>')
        elif line.startswith('> '):
            html_lines.append(f'<blockquote>{_inline_md(line[2:])}</blockquote>')
        elif re.match(r'^\d+\.\s', line):
            if not html_lines or not html_lines[-1].endswith('</ol>'):
                if html_lines and html_lines[-1].startswith('<li'):
                    pass
                else:
                    html_lines.append('<ol>')
            _stripped = re.sub(r'^\d+\.\s', '', line)
            html_lines.append(f'<li>{_inline_md(_stripped)}</li>')
        elif line.startswith('- '):
            if not html_lines or not (html_lines[-1].startswith('<li') or html_lines[-1] == '<ul>'):
                html_lines.append('<ul>')
            html_lines.append(f'<li>{_inline_md(line[2:])}</li>')
        elif line.strip() == '---':
            html_lines.append('<hr/>')
        elif line.strip() == '':
            html_lines.append('')
        else:
            html_lines.append(f'<p>{_inline_md(line)}</p>')

    if in_code:
        html_lines.append('</code></pre>')
    if in_table:
        html_lines.append('</tbody></table>')

    # Close open lists
    result = '\n'.join(html_lines)
    result = result.replace('</li>\n<h', '</li></ul>\n<h')
    result = result.replace('</li>\n<p', '</li></ul>\n<p')
    return result


_SAFE_ANCHOR_SCHEMES = ('http://', 'https://', 'mailto:', '#', '/', '.')


def _safe_href(url: str) -> str:
    """SEC-003 · Only allow http/https/mailto/relative/anchor URLs — everything
    else (javascript:, data:, vbscript:, etc.) is replaced with '#blocked'."""
    if not url:
        return '#'
    u = url.strip()
    lu = u.lower()
    for scheme in _SAFE_ANCHOR_SCHEMES:
        if lu.startswith(scheme):
            return _html_escape(u)
    return '#blocked'


def _inline_md(text: str) -> str:
    import re
    # SEC-003 · Fully escape before doing markdown transforms so ANY HTML
    # meta-chars in user-controlled content (target, evidence, payloads) are neutered.
    text = _html_escape(text)
    text = re.sub(r'\*\*([^*]+)\*\*', r'<strong>\1</strong>', text)
    text = re.sub(r'\*([^*]+)\*', r'<em>\1</em>', text)
    text = re.sub(r'`([^`]+)`', r'<code>\1</code>', text)
    # Anchors — sanitize href scheme
    def _anchor_sub(m):
        label = m.group(1)
        # Unescape quotes back for URL scheme detection then re-escape via _safe_href
        raw_href = (m.group(2)
                    .replace('&quot;', '"').replace('&#39;', "'")
                    .replace('&amp;', '&').replace('&lt;', '<').replace('&gt;', '>'))
        return f'<a href="{_safe_href(raw_href)}" rel="noopener noreferrer">{label}</a>'
    text = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', _anchor_sub, text)
    return text
